adam:
  name: Adam
  lr: 0.001
  betas:
    - 0.9
    - 0.999
  eps: 1e-08
  weight_decay: 0
  amsgrad: false

nadam:
  name: Nadam
  lr: 0.002
  betas:
    - 0.9
    - 0.999
  eps: 1e-08
  weight_decay: 0
  amsgrad: true

weightedadam:
  name: WeightedAdam
  lr: 0.001
  betas:
    - 0.9
    - 0.999
  eps: 1e-08
  weight_decay: 0
  amsgrad: false
  class_weights:
    - 1
    - 2

adagrad:
  name: Adagrad
  lr: 0.01
  lr_decay: 0
  weight_decay: 0
  initial_accumulator_value: 0
  eps: 1e-10

adamax:
  name: Adamax
  lr: 0.002
  betas:
    - 0.9
    - 0.999
  eps: 1e-08
  weight_decay: 0

optimizer_general:
  lr: 0.001
  betas:
    - 0.9
    - 0.999
  eps: 1e-08
  weight_decay: 0